pub const VALID_COLORS: [&str; 19] = [
    "none",
    "black",
    "red",
    "green",
    "yellow",
    "blue",
    "magenta",
    "purple",
    "cyan",
    "white",
    "bright black",
    "bright red",
    "bright green",
    "bright yellow",
    "bright blue",
    "bright magenta",
    "bright purple",
    "bright cyan",
    "bright white",
];
